RANDOM_SEED: 0
FP16_OPT: 2

DATA:
  ROOT: "datasets/imagenet"
  IMAGE_TRANSFORM_TRAIN:
    - "random_resized_crop"
    - "horizontal_flip"
    - "normalize"
  IMAGE_TRANSFORM_VAL:
    - "smallest_resize"
    - "center_crop"
    - "normalize"

MODEL:
  VISUAL:
    FROZEN: true

OPTIM:
  BATCH_SIZE: 256
  SGD_MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0
  NO_DECAY: "none"
  USE_LOOKAHEAD: False

  LR: 0.3
  WARMUP_STEPS: 0
  LR_DECAY_NAME: "multistep"
  LR_GAMMA: 0.1
  LR_STEPS:
    - 300300  # 60 epochs
    - 400400  # 80 epochs
  NUM_ITERATIONS: 500500  # 100 epochs
